### ISSUE TITLE
Question: Where in Angular did you use Tensorflow.js?

### ISSUE THREAD

**Issue by jek-bao-choo** [martzcodes/tensorflow-toxicity-chrome-extension#1]
Could you point me to the file in Angular that you used Tensorflow.js?

Also could you share with me how did you train your ML model for identifying toxic words?

I am asking for my learning and all other Angular readers.

**Comment by martzmakes** [comment]
TensorflowJS is used here: https://github.com/martzcodes/tensorflow-toxicity-chrome-extension/blob/master/projects/toxicity-lib/src/lib/toxicity-lib.service.ts

This was using a pre-trained model (not my own)... which is described here:  https://github.com/tensorflow/tfjs-models/tree/master/toxicity  and here: https://medium.com/tensorflow/text-classification-using-tensorflow-js-an-example-of-detecting-offensive-language-in-browser-e2b94e3565ce
